services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/core:/app/app/core

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
